### ISSUE TITLE
Would you like to make it a grabber?

### ISSUE THREAD

**Issue by nichevulcan20** [JavaNameConvention/ChromePasswordExport#1]
The grabber can pass the info through a discord webhook to us, of the victim. Basically victim will open the file and we will get his passwords can you do it without any packages?

**Comment by JavaNameConvention** [comment]
This was initially designed just for a user to get chrome passwords on his or her computer, and if I wanted to make it a password grabber, I would open up a new project. However, you can do that if you wish with my project
